# Deploys a new Namespace for the mysql Pod
apiVersion: v1
kind: Namespace
metadata:
  name: dsc # Change this value if you want a different namespace name
  labels:
    name: dsc # Change this value to match metadata.name
---

# Deployment for service
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: dsc
spec:
  type: NodePort
  selector:
    app: mysql
  ports:
    - port: 3306
      # By default and for convenience, the `targetPort` is set to
      # the same value as the `port` field.
      targetPort: 3306
      # Optional field
      # By default and for convenience, the Kubernetes control plane
      # will allocate a port from a range (default: 30000-32767)
      nodePort: 30009
---   

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: dsc
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:8.0.32
        name: mysql
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: Deeptanshu1!!
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim