# Deployment for service
apiVersion: v1
kind: Service
metadata:
  name: minio-service
  namespace: minio-dev
spec:
  type: NodePort
  selector:
    app: minio
  ports:
    - port: 9000
      name: minio-backend
      # By default and for convenience, the `targetPort` is set to
      # the same value as the `port` field.
      targetPort: 9000
      # Optional field
      # By default and for convenience, the Kubernetes control plane
      # will allocate a port from a range (default: 30000-32767)
      nodePort: 30007
    - port: 9090
      name: minio-dashboard
      # By default and for convenience, the `targetPort` is set to
      # the same value as the `port` field.
      targetPort: 9090
      # Optional field
      # By default and for convenience, the Kubernetes control plane
      # will allocate a port from a range (default: 30000-32767)
      nodePort: 30008